---
- name: Add VLANs using loops
  hosts: SPINES
  tasks:
    - name: Add VLANs
      arista.eos.eos_vlans:
        config:
          - vlan_id: "{{ item['id'] }}"
            name: "{{ item['name'] }}"
            state: active
        state: merged
      loop: "{{ global_vlans }}"
