---
- name: Add VLANs
  hosts: a-leaf1
  tasks:
    - name: Add VLAN 10
      arista.eos.eos_vlans:
        config:
          - vlan_id: 10
            name: DMZ
            state: "active"
        state: merged